name: style-transfer

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - name: deploy
        env:
          repo_token: ${{ secrets.REPO_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: |
          cml-runner \
            --cloud aws \
            --cloud-region us-west  \
            --cloud-type t2.micro \
            --cloud-spot \
            --labels=cml-runner-gpu \
            --cloud-ssh-private="-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEA5TslCQJX5qkJExzH70lIsudQeaUGNh7sImQPS0QnRbwcbuRP\n5R/bInyGj7aLrATdWkpaP9LfN3lRICvM830Ulazndr4q+C4PxRwT8zeRQLElbXBE\njYrBcsEf97h9I6LiwRKPh+KDwuXHrencvfNfdXm85IrtIcUXdYKmevNrNF37m5Xi\ne78l1/tqyeAmH7ESVO67gh0YlRyDMJjMXWSDrr9VfGidAPChSN7X3WB6z4S4uIL3\ncxyTDcbFexXV3JmKoHVLbrZ0jX9W9krthe04Vfw60HgUTUXiY4HGI8/jvPN5Vj+n\nqyjRdY735DSQLWPdcrHiBaRdib4iBOC3SnPmwTgYTJUolxlM707Cl0rgeveHoEI/\nGYXJtIwuzEDsIlnL4RP4qk6yLiImdJH6sxbvuMsYwZUOWfHd7MeWM9kQy/viPJsO\n217Elnxg0XapA+EmGXr83YVt3TxGjdfAUcGhthzUJQ8lB15j+QZpJVmZi8Yz17g7\nsmo2gSJG/Fq/YVJVUgVS/YjyVa+QA8F9ik/oY2XMtaplyi5j7m+dTrYwSwEQdCDZ\nX64gK58GHPnwwWvBEgx/fD4LwSZt1F/kTms4tGUoIdX3TOQHOue5GKJZG1rBMECA\ngmZUqVY9fvPzhhLUpOypEo/6r+3K2TGZnCrAWzMI9v6Nc4yICL2Zu4756KUCAwEA\nAQKCAgEAtCIiHE5HHO9APlCjnJoOEuhLCQxxMR5jmTLgAdlwsw/7l/i5/+dkoFkS\ntORSJb884rMC8JyY5FLlOU6yI7Tq9COHUHxn79bidZZ25u2HqzqJmtJaTI/5LGAu\n6s+DJvndDrOzLqkFuaYvn67i1DHnlb0wfrfdWGg04xbkFEIswF4KVl0WOQAgkPT1\nGeaWjtjq+usPVlPe+W4KeanZDprqD+wzFSxwFEkDtOvI3iHu4Bv/vJ7OLRsLRAwr\nK2ohQNU3ZphFyp5+QKMMh0aiGFgtqQQog6GY8pA0MtXMCmBXKih59RjYfVv6HVNX\n4XCcy85qOrMmViCvkIpk2UhtQIiLj1Xm1Da1i3utDFehjOHZpYSlCLk9JgoRn9W4\n3y3ItuzvsfErlVh20MDm+qnPH9FEtPnxREBUp6V+Gt+4jyiR+AX3Yw3yDUs74IW7\nxajHN9+UkUzgNQq7LP8YbkX53U64brzyK6C0KMmckgfrgDW2FG5ra1ig1poQbfNn\nK+Zywjrd5nUGYvzs9/SMFY+wE+gGV6+PEVUcHCArVzxX08eodlUkFkrEhV9dj5Dd\n3cft18psRoKTxHmW3M2Q9p/f8U1ALL4FC+d73psJxvgYQQb8IS9tFQ88B8Io0Wcj\nUMuHrJIKdiondbq67ZwuvOgYE4sE3Fu5De0SQmjPOf7jxQ8lO4ECggEBAO3Yl91O\nJzbB1Dn3QOAylLGZ2mRQmGTY9ANHssZl+yjp7dPV8X/aPrsMLnlHPVT9ZSCJqFes\ngv1mkC+XUEGpKpuikAQw1qGWbpN+OX9BNL0OYsWtvhRTn/on5xVVKgGHRZSrx9Uk\nXwvb+BmzSmv2eJ5MKjqrUkL6c1HTyXxCSQHkLtCJc2BceJdnRG36PazepavrpiHY\nEW/KRyn1J6M/REFs8JwNTo18cLDVdy0Tb1CNygACZrxf62ogBoqIFWnGLVlqxQGb\nrQIdbhbDuYd23S31/bfgjlE9SlauiXpHpCuRDu2cW+SC2v7GNrZw8inDxKwaSbbM\nw4ZVND9k8x1eeM0CggEBAPa6N67gh8dhQD13bTnfZIWfce1pXjyt+U4u6gsT2/am\nlWp/8W+Zyw6fVhlJ4/MyBbrK6sizioMaC+/sXPl8ByPYeUiFUm/ybVW51eGCaPc2\noM8wnKxfxfIuVSpeadwwpGarWpFaEPDG+faGc8lbrrO04u/kpUsrO4HifXbDXCD1\nonIu7PFy3UQKtnqs255asDIkBhuVuoNFQDzGCXM8bz+Onndw+tvJz/mYld1Zjd/t\nYuWvQTk9K95lNLnysfN2QXZs9s3/DnXD2jVapwcDr6HlcPJHwVlE2MjvVaM5wCwl\nLtuHmBkVIN+G8hm0d3wA/D+GD8XF+qvmQ8Ahjk9RDzkCggEAGKVT/zuk9piZLDSB\nxXmYTNr7dV+gmvqcNmbMkKBqqS+sVEIcFzp/O5SkkC6gnVjwjLGW/xbCMA3brQLJ\n7zPfVWc/8x84bmAPLztqK9SO6XQ/Keq6ApMzxZEy8dP0WVoyDJjMSTrOmoT9rXQV\npyBQGV8dFR1Ble0r2/PNMhIQTKDfdP55NSf/2vh5b8f5chtUIX92pJUmIWZdf2yG\n4fShVwI54IHEfQbDCp/kDIiyBS/cGaomCSkLVODirKIzTdWaR2S361W9VLXF/Zfk\ndrQLcULHOrGLLcHjHR5S4pff3B/Y4yhLoV8p4DKb4sXLYiaGD6tdrhKDxDy6AEOu\nqYFrlQKCAQEAgkrqtvYpnffUheE4lDRNkGcYMejP9Dlni4so23q8UW+9PgWcyXOt\nEObCAA7OSxKihfc8r4po3jz2CtiGbNW7q4lY2xxU4Xtjk77UnQdSSSLXHzMrubfF\n/9PJ89ryCm7BktpwtIucoJpjTHXKVY6OHqaqpUbYp26IOVoTKZGXaGxvQd9YD1W6\nVYFWxkfcnq6Dl6cAdrbGTSZX+wAV434JvcWiF69ZOpJDuyqCEeeGDbf93w+C4ShV\nr1dA1eW9ZbWQcmqulzBXQYeRB1X9GK4wpM1WrQuJpou987a4Qb9wpZ9pNFNR1gUb\nXA+WcE6mPp0CmMVCNQ4NB5RNOPw/e9FxuQKCAQANbmEWTRz44aQ/MqNZHcblTzDR\nMlKZKxfLzi/8U+aTTOwdsbn5joPmWTKyCfWDDE0RSVptL8tT/PZYuyEhEocJzQju\nY4gCtOsVt215K425Umjew0JGF4IiPWT9bXfm4J05TgDoMegaRPgdMjipU9jWsxZn\nTuYaBKBZEcQflRZTseYmQtPJzhtoAwGa4XA5N0inruSkohge7KlYzmj9E9MdmwR8\nbXYhzEhL3N6R/oyp00OcGoW6W5/gBJxkN0fUD7fr5cn60x/EiKl51AUVADg/XHk/\neuz/kl6/kH5JFBjUWp6I7UVIwBES+gCYMCIb7MHqNXk0ZDny0B/lrvB59ng8\n-----END RSA PRIVATE KEY-----\n"

          cat ./.cml/main.tf
          
  train:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner-gpu]
    #runs-on: [ubuntu-latest]
    container:
      image: davidgortega/cml:python
      #options: --gpus all
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.4'

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: iterative/setup-cml@v1

      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN}}
        run: |
          curl https://google.com
          
          apt update -y
          apt install imagemagick -y
          
          yes | pip install -r requirements.txt
          
