name: style-transfer

on: [push]

jobs:
  # deploy-runner:
  #   runs-on: [ubuntu-latest]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: iterative/setup-cml@v1

  #     - name: deploy
  #       env:
  #         repo_token: ${{ secrets.REPO_TOKEN }} 
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       run: |
  #         cml-runner \
  #           --cloud aws \
  #           --cloud-region us-west  \
  #           --cloud-type t2.micro \
  #           --cloud-spot \
  #           --labels=cml-runner-gpu
          
  train:
    #needs: deploy-runner
    #runs-on: [self-hosted,cml-runner-gpu]
    runs-on: [ubuntu-latest]
    container:
      image: davidgortega/cml:python
      #options: --gpus all
    
    steps:
      - uses: actions/checkout@v2

      - name: print dist
        run: |
          lsb_release -a
          git version

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.4'

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: iterative/setup-cml@v1

      - name: cml_run
        env:
          repo_token: ${{ secrets.REPO_TOKEN}}
        run: |
          pip install -r requirements.txt
          
